### ISSUE TITLE
vinao

### ISSUE THREAD

**Issue by vanilanorca** [bzangi/1-time-invest-landing-page#1]
```
//bg fixo
section#atendimento{
background-attachment: fixed;
box-shadow: inset -5px -5px 5px 0px #0000008f
}

.footer-text{
word-wrap: break-word
}

section#assessoria li{
align-items: center
}
```

<video id="bgVideo" preload="true" autoplay="" loop="" muted="">
(remover [controls = "false"])

**Comment by bzangi** [comment]
Thanks for your suggestion, the improvements are now live. Check it out! [bruno-one-time-invest.netlify.app](https://bruno-one-time-invest.netlify.app/)

**Comment by bzangi** [comment]
Thanks for your suggestion, the improvements are now live. Check it out! [bruno-one-time-invest.netlify.app](https://bruno-one-time-invest.netlify.app/)
